### ISSUE TITLE
Здравствуйте

### ISSUE THREAD

**Issue by Mobsman** [SLabuzov/twitter#14]
@Bean
    public SecurityFilterChain securityFilterChain(HttpSecurity http) throws Exception {

        http.csrf(AbstractHttpConfigurer::disable)
                .cors(CorsConfigurer::disable)
                .sessionManagement(session -> session.sessionCreationPolicy(SessionCreationPolicy.STATELESS))
                .authorizeHttpRequests(auth -> auth
                        .requestMatchers("/api/registrations").permitAll()
                        .requestMatchers("/api/login").hasRole("USER")
                        .anyRequest().authenticated())
                .httpBasic(Customizer.withDefaults());

        return http.build();

@Service
@Transactional
public class UserService implements UserDetailsService {

    private final UserRepository userRepository;
    private final RoleRepository roleRepository;
    private final PasswordEncoder passwordEncoder;

    public UserService(UserRepository userRepository, RoleRepository roleRepository, PasswordEncoder passwordEncoder) {
        this.userRepository = userRepository;
        this.roleRepository = roleRepository;
        this.passwordEncoder = passwordEncoder;
    }

    public void addNewUser(UserRequest request) {
        UserRole userRole = roleRepository.getUserRoleByAuthority("USER").orElseThrow(RuntimeException::new);
        UserAccount user = new UserAccount();
        user.setUsername(request.getUserName());
        user.setPassword(passwordEncoder.encode(request.getPassword()));
        user.setAuthorities(Set.of(userRole));
        userRepository.save(user);
    }

    @Override
    public UserDetails loadUserByUsername(String username) throws UsernameNotFoundException {
        User user = userRepository.findUserByUsername(username)
                .map(userAccount ->
                        new User(userAccount.getUsername(),userAccount.getPassword(),
                                userAccount.getAuthorities().stream()
                                        .map(authority -> new SimpleGrantedAuthority(authority.getAuthority()))
                                        .collect(Collectors.toList())))
                .orElseThrow(() -> new UsernameNotFoundException("Unknown user: " + username));

        return user;

    }
}

@Entity(name = "users")
public class UserAccount {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;
    @Column(name = "username")
    private String username;
    @Column(name = "password")
    private String password;
    @ManyToMany(fetch = FetchType.EAGER)
    @JoinTable(name = "user_roles",
            joinColumns = {@JoinColumn(name = "user_id", referencedColumnName = "id")},
            inverseJoinColumns = {@JoinColumn(name = "role_id", referencedColumnName = "id")
            })
    private Set<UserRole> authorities = new HashSet<>();

**Comment by SLabuzov** [comment]
@Mobsman добрый день. Опишите, пожалуйста, в чем суть ошибки.
+Скрин в режиме DEBUG как сформировался объект user
![image](https://github.com/SLabuzov/twitter/assets/122205023/a5b85671-da57-4aa5-8807-09c5279d266c)

**Comment by Mobsman** [comment]
@Override
    public UserDetails loadUserByUsername(String username) throws UsernameNotFoundException {
        return userRepository.findUserByUsername(username)
                .map(userAccount ->
                        new User(userAccount.getUsername(),userAccount.getPassword(),
                                userAccount.getAuthorities().stream()
                                        .map(authority -> new SimpleGrantedAuthority(authority.getAuthority()))
                                        .collect(Collectors.toList())))
                .orElseThrow(() -> new UsernameNotFoundException("Unknown user: " + username));
    }   все равно 403

**Comment by Mobsman** [comment]
![image](https://github.com/SLabuzov/twitter/assets/86927837/82018c48-01a0-49d3-9464-6eac12946d6d)

**Comment by SLabuzov** [comment]
@Mobsman Мне кажется проблема кроется в самих ролях.
Вместо *USER* необходимо в БД положить ***ROLE**_USER*
Как результат на выходе получаете 403.
https://docs.spring.io/spring-security/reference/servlet/authorization/architecture.html

![image](https://github.com/SLabuzov/twitter/assets/122205023/19f1417d-0cbf-45b5-a3d3-ff2ad6717081)

**Comment by Mobsman** [comment]
у меня в бд USER или спрингу нужно жесткое название?

**Comment by SLabuzov** [comment]
В БД нужно сохранить как ROLE_USER

**Comment by Mobsman** [comment]
заработало, спасибо большое
