### ISSUE TITLE
Issue with jacoco 

### ISSUE THREAD

**Issue by Bugaienko** [SLabuzov/twitter#22]
https://github.com/Bugaienko/Mytwitter_restAPI

**Comment by Bugaienko** [comment]
![image](https://github.com/SLabuzov/twitter/assets/104263728/ab644e50-aa9e-48b0-963b-df25bf45018c)

Build file 'F:\All JAVA projects\Twitter\build.gradle' line: 64

A problem occurred evaluating root project 'twitter'.
> Could not find method enabled() for arguments [true] on Report xml of type org.gradle.api.reporting.internal.TaskGeneratedSingleFileReport.

**Comment by SLabuzov** [comment]
![image](https://github.com/SLabuzov/twitter/assets/122205023/1d2cf435-9f36-4972-a4e9-fa41eefa439a)

В версии gradle 8*  (в вашем примере используется gradle версии 8.5) данный конфиг не работает. Скорее всего он стал Deprecated.
