### ISSUE TITLE
Models instead of DTOs

### ISSUE THREAD

**Issue by MelnykVL** [SLabuzov/twitter#26]
Hi!

Why do you use models for requests and responses?
There are DTOs for requests and responses in the following project:
_https://github.com/MelnykVL/Gravity-SDOH-Exchange-RI/tree/main/cp/app/src/main/java/org/hl7/gravity/refimpl/sdohexchange/dto/request_
Is it a bad approach?
or is your point that DTOs mustn't contain validation logic and constraints like **NotNblak**, **Size** etc?

**Comment by SLabuzov** [comment]
Hey, @MelnykVL!

These are the same DTOs or “DTO models”. 🙂 
It seems to me that it would be more informative to indicate in the name that this object is used as a request or response.

**Comment by MelnykVL** [comment]
Got it, thanks)
