### ISSUE TITLE
05 Создание профиля пользователя. Во время создания тестового пользователя ошибка 401

### ISSUE THREAD

**Issue by aleksashk** [SLabuzov/twitter#27]
https://github.com/aleksashk/demo-twitter-v3/commit/e98e591ef83e6f54ad88e6643623bb914c18e6a7
ссылка на github.
Спасибо за попытку разобраться!!)

**Comment by SLabuzov** [comment]
А можете поделиться скрином как формировали запрос на создание профиля пользователя?
Есть предположение, что просто не указали креды при выполнении запроса

**Comment by aleksashk** [comment]
![Снимок экрана 2024-05-21 172921](https://github.com/SLabuzov/twitter/assets/40260846/527c1eac-2218-4ce9-8019-1e487c5ee662)

**Comment by aleksashk** [comment]
Вроде бы разобрался, проблема в невнимательности, я не указал в postman во вкладке Authorization->Basic Auth
Но вам все равно большое спасибо за труд, очень полезно для многих начинающих!!! Если еще будут вопросы, можно будет так же обращаться?

**Comment by SLabuzov** [comment]
> Вроде бы разобрался, проблема в невнимательности, я не указал в postman во вкладке Authorization->Basic Auth Но вам все равно большое спасибо за труд, очень полезно для многих начинающих!!! Если еще будут вопросы, можно будет так же обращаться?

Обязательно обращайтесь
