### ISSUE TITLE
вопрос по авторизации учебного проекта "twitter"

### ISSUE THREAD

**Issue by thegreatestacc** [SLabuzov/twitter#29]
добрый вечер. в продолжении беседы под комментариями к данному видео https://www.youtube.com/watch?v=44Kh0a1jmvo&list=PLWw-leBindLFIUYLXSVg37L8p4zHXVQcp&index=9

перепроверил. запрос отправляю с кредами, но не через postman, а через http файл в идее (назвал его requests.http, лежит в корневой папке проекта). если у вас будет время, не могли бы вы посмотреть/спулить проект. актуально для ветки master (пока что в нее лить ни чего не буду)

ссылка на гит - https://github.com/thegreatestacc/twitter
заранее благодарю :)

**Comment by SLabuzov** [comment]
Добрый вечер.
Так вроде же отсутствуют креды 😃 
 
Authorization: Basic new_demo_user@gmail.com new_demo_password

**Comment by thegreatestacc** [comment]
да, вы правы. видимо у меня глаз замылился и я не на тот реквест смотрел.
благодарю за ревью
