### ISSUE TITLE
вопрос по использованию @EntityListeners

### ISSUE THREAD

**Issue by thegreatestacc** [SLabuzov/twitter#30]
Добрый день!
урок - https://www.youtube.com/watch?v=k-pVHHda9VQ&list=PLWw-leBindLFIUYLXSVg37L8p4zHXVQcp&index=6

Решил погуглить подробнее как работать с @EntityListeners.
В примере Вы создаете сущность tweet и в ней создаете поле createdTimestamp для отслеживания даты создания твита. Я наткнулся на статью, в которой предлагается унаследоваться от абстрактного класса AbstractAuditable, в котором уже реализованы методы которые сеттят дату создания, дату изменения и еще пару методов.
Вопрос. 
Что на Ваш взгляд лучше использовать с технической точки зрения? Делать поле в сущности для даты создания или унаследоваться от AbstractAuditable? Может есть какие то технические тонкости?
Если в бизнестребованиях прописано отслеживать только дату создания твита, то реализация с одним полем в сущности, как мне кажется, достаточна :)
Заранее благодарю.

ссылка на статью - https://habr.com/ru/articles/238487/

**Comment by SLabuzov** [comment]
Добрый день!
Здесь все просто, если Вам нужна информация лишь о дате создания/изменения объекта, то правильнее будет НЕ использовать AbstractAuditable. Так как придется каждую табличку расширять атрибутами как createdBy, lastModifiedBy.

Если нужно все 4 атрибута отслеживать, лучше перейти к использованию AbstractAuditable.

НО:
Реализация AbstractAuditable сохраняет даты как Date, в своей же реализации Вы не будете ограничены Date.

**Comment by thegreatestacc** [comment]
Благодарю за ответ :)
