### ISSUE TITLE
Вопрос по наименованию классов

### ISSUE THREAD

**Issue by thegreatestacc** [SLabuzov/twitter#31]
Добрый день!
Возник вопрос по поводу наименования двух классов.
TweetAddUseCaseFacade и TweetEditUseCaseImpl.
Как я понял, для редактирования твита класс должен называться TweetEditUseCaseFacade, потому что это не сервис, который работает с твитами, а компонента для обработки случая редактирования твита.
Или я что то не правильно понял?

Благодарю за ответ

https://github.com/SLabuzov/twitter/blob/edit_tweet/src/main/java/dev/simpleapp/twitter/user/tweet/usecase/impl/TweetEditUseCaseImpl.java

https://github.com/SLabuzov/twitter/blob/edit_tweet/src/main/java/dev/simpleapp/twitter/user/tweet/usecase/impl/TweetAddUseCaseFacade.java

**Comment by SLabuzov** [comment]
@thegreatestacc да, вы правы, название должно быть **TweetEditUseCaseFacade**

Спасибо за замечание
